# Generated by Django 4.1.3 on 2023-04-11 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0012_alter_user_entity"),
        ("Asset", "0003_assetclass_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="User.user"
            ),
        ),
    ]
