# Generated by Django 4.1.3 on 2023-04-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0004_alter_asset_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="property",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
