# Generated by Django 4.1.3 on 2023-04-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0006_asset_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
