# Generated by Django 4.1.3 on 2023-04-18 01:23

from django.db import migrations, models
import utils.model_date


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0007_asset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='expire',
        ),
        migrations.AddField(
            model_name='asset',
            name='create_time',
            field=models.DateTimeField(default=utils.model_date.get_current_time),
        ),
        migrations.AddField(
            model_name='asset',
            name='expire_time',
            field=models.DateTimeField(default=utils.model_date.get_datetime),
        ),
    ]
