# Generated by Django 4.1.3 on 2023-04-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0008_remove_asset_expire_asset_create_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='expire_time',
            new_name='expire',
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
