# Generated by Django 4.1.3 on 2023-04-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0009_rename_expire_time_asset_expire_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrequests',
            name='request_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pendingrequests',
            name='review_time',
            field=models.DateTimeField(),
        ),
    ]
