# Generated by Django 4.1.3 on 2023-04-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0010_alter_pendingrequests_request_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='department',
        ),
    ]
