# Generated by Django 4.1.3 on 2023-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0011_remove_asset_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
    ]
