# Generated by Django 4.1.3 on 2023-04-20 03:43

from django.db import migrations, models
import utils.model_date


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0012_alter_asset_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrequests',
            name='asset',
        ),
        migrations.AddField(
            model_name='pendingrequests',
            name='asset_list',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingrequests',
            name='request_time',
            field=models.DateTimeField(default=utils.model_date.get_current_time),
        ),
        migrations.AlterField(
            model_name='pendingrequests',
            name='review_time',
            field=models.DateTimeField(null=True),
        ),
    ]
