# Generated by Django 4.1.3 on 2023-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0013_remove_pendingrequests_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='property',
            field=models.TextField(null=True),
        ),
    ]
