# Generated by Django 4.1.3 on 2023-04-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_rename_url_app_path'),
        ('Asset', '0015_remove_pendingrequests_asset_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequests',
            name='asset_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PendingRequests_asset_admin', to='User.user'),
            preserve_default=False,
        ),
    ]
