# Generated by Django 4.1.3 on 2023-04-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0016_pendingrequests_asset_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequests',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asset.assetclass'),
        ),
    ]
