# Generated by Django 4.1.3 on 2023-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0017_pendingrequests_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
