# Generated by Django 4.1.3 on 2023-04-24 14:01

from django.db import migrations, models
import django.db.models.deletion
import utils.model_date


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0014_rename_url_app_path"),
        ("Asset", "0019_assetclass_selfprop"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingResponse",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.IntegerField()),
                ("more_info", models.CharField(max_length=128, null=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "response_time",
                    models.DateTimeField(default=utils.model_date.get_current_time),
                ),
                ("read_time", models.DateTimeField(null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Asset.asset"
                    ),
                ),
                (
                    "asset_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PendingResponse_asset_admin",
                        to="User.user",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PendingResponse_employee",
                        to="User.user",
                    ),
                ),
            ],
        ),
    ]
