# Generated by Django 4.1.3 on 2023-04-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0014_rename_url_app_path"),
        ("Asset", "0020_pendingresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingresponse",
            name="asset_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="PendingResponse_asset_admin",
                to="User.user",
            ),
        ),
    ]
