# Generated by Django 4.1.3 on 2023-05-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0021_alter_pendingresponse_asset_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='label_visible',
            field=models.CharField(default='111111', max_length=128),
        ),
    ]
