# Generated by Django 4.1.3 on 2023-05-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0023_pendingrequests_asset_pendi_result_3b538f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='warn_content',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warn_type',
            field=models.IntegerField(default=2),
        ),
    ]
