# Generated by Django 4.1.3 on 2023-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0024_asset_warn_content_asset_warn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequests',
            name='apply_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pendingrequests',
            name='maintain_time',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pendingrequests',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
