# Generated by Django 4.1.3 on 2023-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0025_pendingrequests_apply_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='loss_style',
            field=models.IntegerField(default=1),
        ),
    ]
