# Generated by Django 4.1.3 on 2023-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0027_alter_assetclass_loss_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingrequests",
            name="message_id",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
