# Generated by Django 4.1.3 on 2023-05-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Asset", "0028_pendingrequests_message_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pendingrequests",
            index=models.Index(
                fields=["message_id"], name="Asset_pendi_message_6f3bd7_idx"
            ),
        ),
    ]
