# Generated by Django 4.1.3 on 2023-04-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0012_alter_user_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=128)),
                ("Is_Locked", models.BooleanField(default=False)),
                ("Is_Internal", models.BooleanField(default=True)),
                ("authority", models.IntegerField()),
                (
                    "entity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.entity",
                    ),
                ),
            ],
        ),
    ]
