# Generated by Django 4.1.3 on 2023-04-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0013_app"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="url",
            new_name="path",
        ),
    ]
