# Generated by Django 4.1.3 on 2023-05-10 03:29

from django.db import migrations, models
import utils.model_date


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0014_rename_url_app_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "create_time",
                    models.DateTimeField(default=utils.model_date.get_current_time),
                ),
                ("type", models.IntegerField()),
                ("user_name", models.CharField(max_length=128)),
                ("more_info", models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
