# Generated by Django 4.1.3 on 2023-05-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0015_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="entity_name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
