# Generated by Django 4.1.3 on 2023-05-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0016_log_entity_name_alter_entity_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="log",
            index=models.Index(fields=["type"], name="User_log_type_1f5e9b_idx"),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["entity_name"], name="User_log_entity__1b8449_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["type", "entity_name"], name="User_log_type_2ad6b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionpool",
            index=models.Index(
                fields=["sessionId"], name="User_sessio_session_2891a2_idx"
            ),
        ),
    ]
