# Generated by Django 4.1.3 on 2023-05-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0017_log_user_log_type_1f5e9b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
