# Generated by Django 4.1.3 on 2023-05-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0020_user_feishu_user_open_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feishu_depart",
            field=models.IntegerField(null=True),
        ),
    ]
