# Generated by Django 4.1.3 on 2023-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0021_user_feishu_depart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feishu",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("feishu_department", models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="feishu_depart",
        ),
    ]
