# Generated by Django 4.1.3 on 2023-05-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0022_feishu_remove_user_feishu_depart"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="is_succ",
            field=models.IntegerField(default=1),
        ),
    ]
