# Generated by Django 4.1.3 on 2023-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0023_log_is_succ"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="image",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
